<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.6">
  <POU Name="MAIN" Id="{282793d0-dd86-449b-919f-f07f679b0527}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	record : ST_Record;
	bla : DWORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[bla := record.test[9999];]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>